### ISSUE TITLE
Make compatible with selfregister plugin

### ISSUE THREAD

**Issue by poVoq** [silinternational/simplesamlphp-module-material#24]
Would be nice if it was also possible to use the self-register plugin with this theme. See:
https://github.com/GEANT/simplesamlphp-module-selfregister

As an example for another theme that is compatible see:
https://github.com/Prodrivers/simplesamlphp-module-theme-prodrivers

Thanks!

**Comment by wcjr** [comment]
I'll take a look, thanks

**Comment by wcjr** [comment]
Just wanted to take a moment to thank you for your suggestion.  

We ended up handling registration internally so we won't have a need for this in our organization but would gladly review any PR's to add it.

Thanks again!
