### ISSUE TITLE
[Low priority] Consider making login form field text color darker

### ISSUE THREAD

**Issue by forevermatt** [silinternational/simplesamlphp-module-material#26]
The current login form fields use a medium grey text color (due to semi-transparency) that ends up looking like `rgb(117, 117, 117)`:

![image](https://user-images.githubusercontent.com/6233204/28426639-c2938f6e-6d41-11e7-9316-e68880124bc7.png)

Since that color is often used for placeholder text, and text entered into a field is often closer to black, it may look better to use `rgb(0, 0, 0)` for the color of text entered into a field, as Google does on their login form:

![image](https://user-images.githubusercontent.com/6233204/28426802-452ec182-6d42-11e7-8382-965bb67bca01.png)

If this ends up requiring manually modifying several minified CSS rules (or for some other reason would be unreasonably painful to do or to maintain), feel free to reject this as not worth the effort.

**Comment by devon-sil** [comment]
Adding to backlog for evaluation.

**Comment by forevermatt** [comment]
It looks like this might have been done in https://github.com/silinternational/simplesamlphp-module-material/pull/136.

**Comment by hobbitronics** [comment]
> It looks like this might have been done in #136.

Yes, it just hasn't been pushed to production in the IDP, but in this repo the issue is resolved.
