### ISSUE TITLE
Review current best practices for favicons

### ISSUE THREAD

**Issue by wcjr** [silinternational/simplesamlphp-module-material#27]
some relevant points made by @fillup on current implementation:

> well, we need a small square graphic for the favicon, but a large other potentially rectangular image for the main logo and ico can support multiple resolutions for different devices/uses

http://www.jonathantneal.com/blog/understand-the-favicon/

Review the latest HTML5 boilerplate as well.

**Comment by forevermatt** [comment]
Based on that link, it looks like this is the conclusion:
> stick the ICO favicon in the root directory and use `<link rel="icon">` to assign the PNG favicon

So if we have a `/favicon.ico` file (with some undecided set of sizes) then also have a `/favicon.png` file referenced using `<link rel="icon" href="path/to/favicon.png">` in the markup (specifically *not* including `shortcut` in that `rel` value), we should end up with a good experience for everybody.

**Comment by forevermatt** [comment]
If/when we get to that point, I've had fairly good success using http://realfavicongenerator.net/ (but that's probably overkill for this situation).

**Comment by wcjr** [comment]
Thanks for distilling that.
