### ISSUE TITLE
Problem installing theme on simplesamlphp 1.14.11

### ISSUE THREAD

**Issue by EdwardNavarro** [silinternational/simplesamlphp-module-material#5]
Hi guys,

I've a problem when try to install the theme in simplesamlphp 1.14.11. Composer show this errors:

```
  Problem 1
    - simplesamlphp/simplesamlphp v1.14.11 requires robrichards/xmlseclibs ~1.4.1 -> satisfiable by robrichards/xmlseclibs[1.4.1, 1.4.2, 1.4.x-dev] but these conflict with your requirements or minimum-stability.
    - simplesamlphp/simplesamlphp v1.14.10 requires robrichards/xmlseclibs ~1.4.1 -> satisfiable by robrichards/xmlseclibs[1.4.1, 1.4.2, 1.4.x-dev] but these conflict with your requirements or minimum-stability.
    - silinternational/simplesamlphp-module-material dev-master requires simplesamlphp/simplesamlphp ^1.14.10 -> satisfiable by simplesamlphp/simplesamlphp[v1.14.10, v1.14.11].
    - Installation request for silinternational/simplesamlphp-module-material dev-master -> satisfiable by silinternational/simplesamlphp-module-material[dev-master].
```

If I update xmlseclibs to 1.4.x the SAML2 not work, this require 2.x

The simplesamlphp/simplesamlphp is updated to 1.14.11.

You can help me?

Thanks!

**Comment by wcjr** [comment]
Thanks for letting us know Ed, we'll take a look and get back to you.  @fillup or @forevermatt , is there a quick answer to this or do we need to fiddle with some deps to get this right?

**Comment by forevermatt** [comment]
I'm not sure. It looks like simplesamlphp 1.14.x requires xmlseclibs 1.4.x, so if you need to use a later version of xmlseclibs (2.x), the problem appears (at first glance) like it's a conflict with what simplesamlphp requires.

@EdwardNavarro, if you remove the `silinternational/simplesamlphp-module-material` requirement from you composer.json file, do you still get a similar error message from composer?

**Comment by EdwardNavarro** [comment]
@wcjr no difference, with dev-master or 1.0.1 the issue is same.

@forevermatt this requirement is not in my composer.json file.

**Comment by wcjr** [comment]
Until I understand the root cause better, sorry I'm not extremely familiar with composer, will removing the minimum stability requirement in our composer.json help you progress?  If it's not urgent we can look at it more to understand what the issue is.  Thanks.

**Comment by EdwardNavarro** [comment]
Hi @wcjr, no problem, i can wait take all the time you need. We want to use your module in our servers to offer a great experience to our users but it's not urgent. 👍

**Comment by wcjr** [comment]
@EdwardNavarro , looks like @forevermatt will be able to start looking at that today :-)

**Comment by forevermatt** [comment]
Hi @EdwardNavarro. It looks like the problem comes from trying to use [`simplesamlphp/simplesamlphp`](https://packagist.org/packages/simplesamlphp/simplesamlphp) with a 2.x version of [`simplesamlphp/saml2`](https://packagist.org/packages/simplesamlphp/saml2). To use `simplesamlphp/simplesamlphp`, you will need to use an earlier version of `simplesamlphp/saml2`, such as `^1.10`.
