### ISSUE TITLE
New codes here browser problems

### ISSUE THREAD

**Issue by longrunningprocess** [silinternational/simplesamlphp-module-material#54]
- [x] "DOWNLOAD" doesn't work on Edge/Win10
- [x] Rendering issue on FF/[macOS|Linux]: only 4 codes show/column even though there were 5 in source (the overflow: hidden on the supporting-text class is cutting them off)
- [x] IE11/Win10, renders codes in a single column always, printing and data: url don't work

introduced in https://github.com/silinternational/simplesamlphp-module-material/releases/tag/5.2.0

**Comment by wcjr** [comment]
IE11 print issue:
![image](https://user-images.githubusercontent.com/4412848/35632308-5040fb14-0674-11e8-8dc7-43bdb98637d6.png)

**Comment by wcjr** [comment]
before merging https://github.com/silinternational/ssp-base/pull/47:

1. disable `print` and `download` for ie11/win10 with unsupported message on hover
2. disable `download` for edge/win10 with unsupported message on hover
3. troubleshoot flexbugs on ff and see if it helps with the rendering issue on ie11 as well.

**Comment by wcjr** [comment]
fixes for 1. & 2. in https://github.com/silinternational/simplesamlphp-module-material/commit/ac155c50b25ccc0097c2b38342e20faf0f38c726

**Comment by wcjr** [comment]
fixed 3 in 7bd09ad
